# Generated by Django 4.2.2 on 2023-06-20 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='desciption',
            new_name='description',
        ),
    ]
